### ISSUE TITLE
Confusing behaviour of the export tool, enigmatic error messages.

### ISSUE THREAD

**Issue by kamil-sita** [AliveTeam/qt-editor#101]
Currently when exporting levels the errors aren't obvious, especially combined with the fact that the export feature is somewhat confusing in itself for a first-time user.

1. Since the export tool is located in the "file" tab the user could expect that "export" is an operation performed on the current file - this is not the case, and I feel like it should be moved to some other tab (potentially a new "tools" tab).

2. If path to either the Path json file or to the LVL file is invalid, a confusing error appears (containing the invalid value). Might be especially confusing for the first-time users:

![image](https://user-images.githubusercontent.com/24254781/149640939-bf5e8fde-ac23-4540-8da6-bb1f08ed6140.png)

**Comment by mouzedrift** [comment]
the new qt-editor version no longer has a reason to export to .lvl files
