### ISSUE TITLE
Issue when add a new camera

### ISSUE THREAD

**Issue by gugelman** [AliveTeam/qt-editor#184]
I have a problem and I don't know how to solve it, when I add a new camera and I try it in-game, I can't get in, I receive an error message: 

missing background animation entry for anim id

Why that error appears to me and how I can solve it?

**Comment by mouzedrift** [comment]
if you have a background animation in that camera try removing it or if you tried changing the id of the background animation to some random value it will blow up

**Comment by gugelman** [comment]
Oh now I understand was wrong, the animation of pipes, thank you very much!
