### ISSUE TITLE
[feature] possibility to explicitly export all types of masks when editing cameras

### ISSUE THREAD

**Issue by krischanlensch** [AliveTeam/qt-editor#185]
Hey!

I'm new to this and I may be wrong.
I could not find any guide on how to do this.

When I edit a camera I only have the possibility to import / export the main background image.
Does the exported PNG follow any special subformat which includes the masks? I wasn't able to find such layer...

Please let me know if I'm wrong. But the feature would be much appreciated for creating new screens / cameras of course.

Thanks!

**Comment by mouzedrift** [comment]
you can change the main image and all the masks but exporting only works with the main image atm. to change the image of a mask just select a mask tab and then click on `Choose image...`

**Comment by krischanlensch** [comment]
Alright! Thanks for the explaination and sorry I didn't try that explicitly.

Greetings! :)

**Comment by mouzedrift** [comment]
now you should be able to export masks as well you can get the latest build from [here](https://ci.appveyor.com/project/paulsapps/qt-editor/builds/45752261/job/uyqjl0mqdb7woa2w/artifacts) if you want to try it
