### ISSUE TITLE
it's not possible to make the spinbox empty which is annoying when entering numbers

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/qt-editor#33]
https://user-images.githubusercontent.com/43358824/144520144-18a18938-1583-4c41-a054-af8f6d667826.mp4

**Comment by paulsapps** [comment]
@mouzedrift not sure this can be allowed else you could delete the number and exit the spin box, it has to have some value when you drop focus

**Comment by mouzedrift** [comment]
well if the number is invalid on exit you could set it to what it was before? 🤔

**Comment by paulsapps** [comment]
I guess 🙉
