### ISSUE TITLE
opening already modified .lvl files crashes the editor

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/qt-editor#47]

**Comment by paulsapps** [comment]
![edited_lvl](https://user-images.githubusercontent.com/7420121/144913523-b579674c-4bf9-438d-b5a2-bfdc26ec4105.gif)

can't repro

**Comment by paulsapps** [comment]
problem is reloading the cam crashes in the API because it thinks the cam should have AE FG1 which isn't the case (yet)
