### ISSUE TITLE
Editor doesn't convert RGB values in ShadowZone into floating point/decimals

### ISSUE THREAD

**Issue by kamil-sita** [AliveTeam/qt-editor#94]
**AppVeyor build:** 189, versions before probably also affected

**Relevant screenshot:**

![image](https://user-images.githubusercontent.com/24254781/148650019-9152cf17-23e3-4813-9477-5f14dc00d891.png)

**Comment by mouzedrift** [comment]
fixed in the new qt-editor version which uses a color picker instead
